#Here is our overriding settings for the GCP server and our stock information that we will be pulling.

gcp:
  project_id: algo-strategies-431715
  bucket_name: dl-strat-data

yfinance:
  use_preprocessed: true # If true, use preprocessed, if false, fetch new raw data.
  optimized_features: # List of optimized features we will use for modeling and cointegration based on correlation testing and VIF calculation.
    - 'ATR_14_sec_Lag_3'
    - 'Momentum_1_Lag_Std_1_3_sec'
    - 'Open_Lag_Std_1_3_sec'
    - 'Momentum_30_Lag_Std_1_3_sec'
    - 'Momentum_50_Lag_Std_1_3_sec'
    - 'Low_Lag_Std_1_3_sec'
    - 'High_Lag_Std_1_3_sec'
    - 'EMA_Lag_Std_1_3_sec'
    - 'MACD_Hist_Lag_Std_1_3_sec'
    - 'OBV_sec'
    - 'MACD_Lag_Std_1_3_sec'
    - 'ATR_14_Lag_Std_1_3_sec'
    - 'MACD_Signal_Lag_Std_1_3_sec'
    - 'OBV_sec_Lag_3'
    - 'Momentum_50_sec_Lag_1'
    - 'Momentum_50_sec_Lag_3'
    - 'Diff_Close_EMA_sec'
    - 'BBU_Lag_Std_1_3_sec'
    - 'BBL_Lag_Std_1_3_sec'
    - 'Volume_Lag_Std_1_3_sec'
    - 'Momentum_7_sec_Lag_3'
    - 'Momentum_3_Lag_Avg_1_3_sec'
    - 'MACD_Hist_sec_Lag_3'
    - 'Momentum_1_sec_Lag_2'
    - 'Momentum_1_sec_Lag_3'
  optimized_features_for_genlist: # Top 5 features from optimized_features above we will use for generating our secondary stocks that showed to have the highest MI Scores from our notebook.
    - 'ATR_14_sec_Lag_3'
    - 'Momentum_1_Lag_Std_1_3_sec'
    - 'Open_Lag_Std_1_3_sec'
    - 'Momentum_30_Lag_Std_1_3_sec'
    - 'Momentum_50_Lag_Std_1_3_sec'
  core_tickers: ['AAPL', 'MSFT', 'GOOG', 'AMZN', 'NVDA', 'META', 'TSLA', 'PFE', 'MA', 'PG']
  start_date: '2019-01-01'
  end_date: '2024-08-15'
  fallback_start_date: '01-01-2021'
  max_secondary_stocks: 200 #Will be dynamically selected when we get to the cointegration testing.
  exogenous_tickers:
    interest_rates_10yr : '^TNX'
    gold : 'GC=F'
    copper : 'HG=F'
    platinum: 'PL=F'
    silver: 'SI=F'
    crude_oil : 'CL=F'
    natural_gas : 'NG=F'
    corn : 'ZC=F'
    wheat : 'ZW=F'
    volatility_index : '^VIX'
    exchange_rate_usd_eur : 'EURUSD=X'
    exchange_rate_usd_jpy : 'JPY=X'
    sp500 : '^GSPC'
    nasdaq_100 : '^NDX'
    dow_jones_industrial_average : '^DJI'
    consumer_confidence_index : 'CCI'
    vanguard_total_world_stock_etf : 'VT'
    us_treasury_bond_etf : 'GOVT'
  csv_paths:
    core_stock_data: 'data/core_stock_data.csv'
    exogenous_data: 'data/exogenous_data.csv'
    secondary_stocks_gen_filtered: 'data/secondary_stocks_gen_filtered.csv'
    core_stock_preprocessed: 'data/core_stock_preprocessed.csv'
    sec_stock_preprocessed: 'data/sec_stock_preprocessed.csv'
    sec_stock_unscaled: 'data/sec_stock_unscaled.csv'
    exo_data_unscaled: 'data/exo_data_unscaled.csv'
    exo_data_preprocessed: 'data/exo_data_preprocessed'
    core_stock_unscaled: 'data/core_stock_unscaled'
    secondary_stocks_gen: 'secondary_stocks_gen'

model_params:
  vif_threshold: 15 # To be adjusted as needed

# Not sure if the below api keys will be needed, but below just in case for later.
alpha_vantage:
  api_key : 'KS7XHPA221VY38VZ'

fmp:
  api_key : 'lIKWxrwETX1CDqPkmxqq4BcshgBzqhnx'

tiingo:
  api_key: '658cee3dc474e0eb068bd2427933ae6b89cc2f7c'

polygon.io:
  api_key: 'AvguOkrKDzOv8j8xA9UyxvApYVEIeJ8b'

eodhd.io:
  api_key: ' 66bbe5beb6a1d9.26421844'
