#Here is our overriding settings for the GCP server and our stock information that we will be pulling.

gcp:
  project_id: algo-strategies-431715
  bucket_name: dl-strat-data

yfinance:
  core_tickers: ['AAPL', 'MSFT', 'GOOG', 'GOOGL', 'AMZN', 'NVDA']
  start_date: '2019-01-01'
  end_date: '2024-06-30'
  fallback_start_date: '01-01-2021'
  max_secondary_stocks: 100 #Will be dynamically selected when we get to the cointegration testing.

secondary_tickers_source: 'data\secondary_tickers_source.csv'
