#Here is our overriding settings for the GCP server and our stock information that we will be pulling.

gcp:
  project_id: algo-strategies-431715
  bucket_name: dl-strat-data

yfinance:
  core_tickers: ['AAPL', 'MSFT', 'GOOG', 'AMZN', 'NVDA', 'META', 'TSLA', 'PFE', 'MA', 'PG']
  start_date: '2019-01-01'
  end_date: '2024-08-15'
  fallback_start_date: '01-01-2021'
  max_secondary_stocks: 200 #Will be dynamically selected when we get to the cointegration testing.
  exogenous_tickers:
    interest_rates_10yr : '^TNX'
    gold : 'GC=F'
    copper : 'HG=F'
    platinum: 'PL=F'
    silver: 'SI=F'
    crude_oil : 'CL=F'
    natural_gas : 'NG=F'
    corn : 'ZC=F'
    wheat : 'ZW=F'
    volatility_index : '^VIX'
    exchange_rate_usd_eur : 'EURUSD=X'
    exchange_rate_usd_jpy : 'JPY=X'
    sp500 : '^GSPC'
    nasdaq_100 : '^NDX'
    dow_jones_industrial_average : '^DJI'
    consumer_confidence_index : 'CCI'
    vanguard_total_world_stock_etf : 'VT'
    us_treasury_bond_etf : 'GOVT'
  csv_paths:
    core_stock_data: 'data/core_stock_data.csv'
    exogenous_data: 'data/exogenous_data.csv'
    secondary_stocks_gen: 'data/secondary_stocks_gen.csv'
    core_stock_preprocessed: 'data/core_stock_preprocessed.csv'

# Not sure if the below api keys will be needed, but below just in case for later.
alpha_vantage:
  api_key : 'KS7XHPA221VY38VZ'

fmp:
  api_key : 'lIKWxrwETX1CDqPkmxqq4BcshgBzqhnx'

tiingo:
  api_key: '658cee3dc474e0eb068bd2427933ae6b89cc2f7c'

polygon.io:
  api_key: 'AvguOkrKDzOv8j8xA9UyxvApYVEIeJ8b'

eodhd.io:
  api_key: ' 66bbe5beb6a1d9.26421844'
